// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBUGYT15vAjkCMrc1n7Te-uk3MyLQPWSKQ",
      authDomain: "nutrai-personal.firebaseapp.com",
      projectId: "nutrai-personal",
      storageBucket: "nutrai-personal.firebasestorage.app",
      messagingSenderId: "375616503764",
      appId: "1:375616503764:web:d951f72f253d91fce5a041",
      measurementId: "G-GG6YK800S2");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQrnTvLOex_WAHDCccIm4xuymltRhXWcg',
    appId: '1:375616503764:android:595d93f5977aef49e5a041',
    messagingSenderId: '375616503764',
    projectId: 'nutrai-personal',
    storageBucket: 'nutrai-personal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsaAYqO09EWbsrlya1R2CPuGsqK5_d2BQ',
    appId: '1:375616503764:ios:d8db16b301f3bcd2e5a041',
    messagingSenderId: '375616503764',
    projectId: 'nutrai-personal',
    storageBucket: 'nutrai-personal.firebasestorage.app',
    iosBundleId: 'com.example.pizzaOrderingApp',
  );
}
